"use client";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useCurrencyFormatter } from "@/components/preferences/PreferencesProvider";
import { categoryActual, totalIncome, totalPlanned, totalSpending, type BudgetMonth } from "@/lib/finance";
import { costFor, type InvestmentAccount } from "@/lib/investmentData";
import styles from "./DemoTransactions.module.css";

const colors = ["var(--chart-primary)", "var(--chart-secondary)", "var(--money-positive)", "var(--chart-tertiary)", "var(--app-accent)", "var(--brand-gold)"];
const history = [{ month: "Mar", value: 22100 }, { month: "Apr", value: 22800 }, { month: "May", value: 23600 }, { month: "Jun", value: 24800 }, { month: "Jul", value: 25500 }, { month: "Aug", value: 26224 }];

export function BudgetReference({ budget }: { budget: BudgetMonth }) {
  const money = useCurrencyFormatter(), spent = totalSpending(budget), planned = totalPlanned(budget), categories = budget.categories.map((c, i) => ({ name: c.name, spent: categoryActual(c), planned: c.plannedAmount, color: colors[i % colors.length] })).sort((a,b)=>b.spent-a.spent);
  return <div className={styles.page}><div className={styles.budgetGrid}>
    <section className={styles.panel}><div className={styles.panelTitle}><h2>Category budgets</h2><span className={styles.monthTag}>{budget.month}</span></div><div className={styles.budgetTotal}><span>Total spent</span><strong>{money.format(spent)} <small>/ {money.format(planned)}</small></strong></div><div className={styles.track}><span style={{ width: `${Math.min(spent/planned*100,100)}%` }} /></div><div className={styles.categoryList}>{categories.map((c)=><div key={c.name}><div className={styles.categoryHead}><span><i className={styles.dot} style={{background:c.color}} />{c.name}</span><strong>{money.format(c.spent)} <small>/ {money.format(c.planned)}</small></strong></div><div className={styles.track}><span style={{width:`${Math.min(c.spent/c.planned*100,100)}%`,background:c.spent>c.planned?"var(--app-danger)":c.color}} /></div></div>)}</div></section>
    <div className={styles.sideStack}><section className={styles.panel}><div className={styles.panelTitle}><h3>Where it goes</h3></div><div className={styles.donutWrap}><ResponsiveContainer><PieChart><Pie data={categories} dataKey="spent" innerRadius="68%" outerRadius="90%" stroke="none" isAnimationActive={false}>{categories.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip formatter={(v)=>money.format(Number(v))}/></PieChart></ResponsiveContainer><div className={styles.donutCenter}><strong>{money.format(spent)}</strong><span>spent</span></div></div><div className={styles.legend}>{categories.slice(0,4).map(c=><div key={c.name}><i className={styles.dot} style={{background:c.color}}/><span>{c.name}</span><strong>{money.format(c.spent)}</strong></div>)}</div></section><section className={`${styles.panel} ${styles.leftToSpend}`}><span className={styles.label}>Left to spend</span><strong>{money.format(planned-spent)}</strong><p>Your plan updates as purchases are added.</p></section></div>
  </div></div>;
}

export function DemoTransactions({ budget }: { budget: BudgetMonth }) {
  const money = useCurrencyFormatter();
  const income = totalIncome(budget);
  const spent = totalSpending(budget);
  const purchases = budget.categories.flatMap((category) => category.purchases);
  const accountTotals = new Map<string, number>();
  for (const purchase of purchases) {
    const account = purchase.accountName ?? "Account not assigned";
    accountTotals.set(account, (accountTotals.get(account) ?? 0) + purchase.amount);
  }
  const accountSpending = [...accountTotals.entries()]
    .map(([account, amount]) => ({ account, amount }))
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 5);
  const largestAccountSpend = accountSpending[0]?.amount ?? 0;
  const items = [...budget.incomeEntries.map(e=>({id:e.id,name:e.source,category:"Income",account:e.owner,date:e.date,amount:e.amount,incoming:true})),...budget.categories.flatMap(c=>c.purchases.map(p=>({id:p.id,name:p.description,category:c.name,account:p.accountName??"Account not assigned",date:p.date,amount:p.amount,incoming:false})))].sort((a,b)=>b.date.localeCompare(a.date));
  return <div className={styles.page}>
    <div className={styles.summary}><Summary label="Money in" value={`+${money.format(income)}`} tone="positive"/><Summary label="Money out" value={`−${money.format(spent)}`} tone="negative"/><Summary label="Net" value={money.format(income-spent)}/></div>
    <section className={`${styles.panel} ${styles.accountChart}`} aria-labelledby="demo-account-spending-title"><div className={styles.chartHeading}><div><span className={styles.label}>Spending by account</span><h3 id="demo-account-spending-title">Where this month&apos;s money came from</h3></div><strong>{money.format(spent)}</strong></div><div className={styles.accountBars}>{accountSpending.map(item=><div className={styles.accountBarRow} key={item.account}><span>{item.account}</span><div className={styles.accountTrack} aria-hidden="true"><i style={{width:`${largestAccountSpend?(item.amount/largestAccountSpend)*100:0}%`}}/></div><strong>{money.format(item.amount)}</strong></div>)}</div></section>
    <section className={`${styles.panel} ${styles.transactionsPanel}`}><div className={styles.tabs}><button className={styles.tab}>All</button><button className={styles.tab}>Income</button><button className={styles.tab}>Expenses</button><span className={styles.count}>{items.length} transactions</span></div><table className={styles.table}><thead><tr><th>Merchant</th><th>Category</th><th>Account</th><th>Date</th><th>Amount</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className={styles.merchant}><span className={styles.merchantIcon}>{item.name.slice(0,1)}</span><strong>{item.name}</strong></div></td><td><span className={styles.categoryChip}><i className={styles.dot} style={{background:item.incoming?"var(--money-positive)":"var(--chart-secondary)"}}/>{item.category}</span></td><td className={styles.subtle}>{item.account}</td><td className={styles.subtle}>{item.date}</td><td className={item.incoming?styles.positive:styles.negative}><strong>{item.incoming?"+":"−"}{money.format(item.amount)}</strong></td></tr>)}</tbody></table></section>
  </div>;
}

export function InvestmentsReference({ accounts }: { accounts: InvestmentAccount[] }) {
  const money=useCurrencyFormatter(), holdings=accounts.flatMap(a=>a.holdings.map(h=>({...h,account:a.name,cost:costFor(h)}))), total=holdings.reduce((s,h)=>s+h.cost,0);
  return <div className={styles.page}><div className={styles.investmentTop}><section className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.label}>Portfolio value</span><p className={styles.portfolioValue}><strong>{money.format(total)}</strong></p><span className={styles.positive}>▲ 2.04% this month</span></div><span className={styles.monthTag}>1Y</span></div><div className={styles.chart}><ResponsiveContainer><AreaChart data={history}><defs><linearGradient id="portfolio-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-primary)" stopOpacity=".28"/><stop offset="100%" stopColor="var(--chart-primary)" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--app-border)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide domain={["dataMin - 800","dataMax + 600"]}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Area dataKey="value" stroke="var(--chart-primary)" strokeWidth={2.3} fill="url(#portfolio-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section><section className={styles.panel}><div className={styles.panelTitle}><h3>Allocation</h3></div><div className={styles.donutWrap}><ResponsiveContainer><PieChart><Pie data={holdings} dataKey="cost" innerRadius="68%" outerRadius="90%" stroke="none" isAnimationActive={false}>{holdings.map((h,i)=><Cell key={h.id} fill={colors[i%colors.length]}/>)}</Pie></PieChart></ResponsiveContainer><div className={styles.donutCenter}><strong>{holdings.length}</strong><span>holdings</span></div></div><div className={styles.legend}>{holdings.slice(0,4).map((h,i)=><div key={h.id}><i className={styles.dot} style={{background:colors[i%colors.length]}}/><span>{h.symbol}</span><strong>{((h.cost/total)*100).toFixed(1)}%</strong></div>)}</div></section></div><section className={`${styles.panel} ${styles.holdingsPanel}`}><div className={styles.panelTitle}><h3>Holdings</h3></div><table className={styles.table}><thead><tr><th>Asset</th><th>Account</th><th>Allocation</th><th>Value</th></tr></thead><tbody>{holdings.map((h,i)=><tr key={h.id}><td><div className={styles.merchant}><span className={styles.merchantIcon}>{h.symbol.slice(0,2)}</span><div><strong>{h.symbol}</strong><span className={styles.subtle}>{h.name}</span></div></div></td><td className={styles.subtle}>{h.account}</td><td><div className={styles.allocationBar}><div className={styles.track}><span style={{width:`${h.cost/total*100}%`,background:colors[i%colors.length]}}/></div><span className={styles.subtle}>{(h.cost/total*100).toFixed(1)}%</span></div></td><td><strong>{money.format(h.cost)}</strong></td></tr>)}</tbody></table></section></div>;
}
function Summary({label,value,tone}:{label:string;value:string;tone?:"positive"|"negative"}){return <div><span className={styles.label}>{label}</span><strong className={tone?styles[tone]:""}>{value}</strong></div>}
